### ISSUE TITLE
WebSocket API V3 is not stable

### ISSUE THREAD

**Issue by coderunner29** [StocksExchange/nodejs-client#4]
Hi, i'm subscribed to `subscribeOrderFillCreated` event, but after few hours it just stop working. No errors in the log and no crashes, it just don't receive any updates after N hours, while I clearly see that there are new trades in web interface. Only restart of the app helps. 

Is there a way to catch disconnects and try to reconnect if connection is lost? Obviously, for trading bots we need to keep the connection alive 24/7

**Comment by StocksDevelopment** [comment]
Hi!
We added show error
https://github.com/StocksExchange/nodejs-client/blob/master/lib/v3/websocket.js#L84-L101

**Comment by projeham** [comment]
> Hi! We added show error https://github.com/StocksExchange/nodejs-client/blob/master/lib/v3/websocket.js#L84-L101

Dear Sir; 
How can I catch the error by my program? I want to get an event when the disconnects occurred.

**Comment by Drengel1990** [comment]
I think we will add throw error
