### ISSUE TITLE
profileInfo

### ISSUE THREAD

**Issue by zeusthealmighty** [StocksExchange/nodejs-client#5]
I am running an express server with node js, this method only works once. 
I run the server, call my endpoint, returns successfully the info, but next time I call it it tells me "Method not found".

**Comment by zeusthealmighty** [comment]
```
router.get('/profile-wallets', function(req, res, next){

    res.setHeader('Content-Type','application/json');
    se.profileWallets({
    }, function (ans) {
        res.send(ans);
    });
});
```

**Comment by zeusthealmighty** [comment]
![Captura de Pantalla 2019-08-01 a la(s) 19 12 38](https://user-images.githubusercontent.com/37151557/62335170-5d975580-b490-11e9-85f2-4ad4f7f3d16c.png)

**Comment by zeusthealmighty** [comment]
A similar issue happens with newProfileWalletByCurrencyId.
But this time the second time I call it it responds with...
![Captura de Pantalla 2019-08-01 a la(s) 19 40 48](https://user-images.githubusercontent.com/37151557/62336126-7f92d700-b494-11e9-9bd8-5633612d0187.png)

**Comment by zeusthealmighty** [comment]
```
router.post('/create-wallet/:coin', function(req, res, next){
    var coin = req.params.coin;
    var currencyId = getCoinId(coin);
    res.setHeader('Content-Type','application/json');
    se.newProfileWalletsByCurrencyId(currencyId, function (ans) {
        res.send(ans);
    });
});
```

**Comment by zeusthealmighty** [comment]
Same happens with newProfileWalletsAddressById

**Comment by Drengel1990** [comment]
Hi!
Please update your client to version 2.2.2. And try again
